### ISSUE TITLE
Work with JSX

### ISSUE THREAD

**Issue by dy** [devongovett/browserify-optional#3]
Trying to apply this transform with JSX files along with babelify
```js
  "browserify": {
    "transform": [
      "babelify",
      "browserify-optional"
    ]
  }
```
and get the error 

```sh
$ browserify -t browserify-optional -t babelify dom.js
Error: Line 4: Unexpected token > while parsing file: C:\projects\jsxify\lib\nanocomponent.js
    at throwError (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.js:1156:21)
    at throwUnexpected (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.js:1213:9)
    at parsePrimaryExpression (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.js:1567:16)
    at parseLeftHandSideExpressionAllowCall (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.
js:1644:61)
    at parsePostfixExpression (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.js:1703:20)
    at parseUnaryExpression (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.js:1784:16)
    at parseMultiplicativeExpression (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.js:1790
:20)
    at parseAdditiveExpression (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.js:1807:20)
    at parseShiftExpression (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.js:1824:20)
    at parseRelationalExpression (C:\projects\jsxify\node_modules\ast-transform\node_modules\esprima\esprima.js:1845:16)
```

Seems that [ast-transform](https://github.com/hughsk/ast-transform) needs esprima updated.

**Comment by dy** [comment]
hughsk/ast-transform#1 fixes that by providing custom parser: [esprima](https://github.com/jquery/esprima) with `jsx` flag or [babel-parser](https://github.com/babel/babel/tree/master/packages/babel-parser).
